/****** Object:  View [dbo].[HorarioView]    Script Date: 7/20/2022 11:15:25 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


ALTER VIEW [dbo].[HorarioView]
WITH SCHEMABINDING
AS
SELECT 
	   H.EMPRESA
      ,H.CLAVE
      ,H.FECHA
      ,H.CORRIDA
      ,H.CODIGOEMPLEADO
      ,H.NOMBRECOMPLETO
      ,H.POSICION
      ,H.DEPARTAMENTO
      ,H.VICEPRESIDENCIA
      ,H.CORREO
      ,H.TELEFONO
      ,H.AUCOD
      ,H.FECHAINI
      ,H.FECHAFIN
      ,H.CODIGOSUPERVISOR
      ,H.NOMBRESUPERVISOR
      ,H.CORREOSUPERVISOR
      ,H.POSICIONSUPERVISOR
      ,H.TELEFONOSUPERVISOR
      ,H.CODIGOHORARIO
      ,H.HORAINI
      ,H.HORAFIN
      ,H.PONCHEENTRADA
      ,H.PONCHESALIDA
	  ,ISNULL(A.AUDES, '') Tipo2
	  ,IIF(CAST(ISNULL(DATEDIFF(MINUTE, PONCHEENTRADA, PONCHESALIDA), 0) / 60.00 as decimal(18,2)) > 0, CAST(ISNULL(DATEDIFF(MINUTE, PONCHEENTRADA, PONCHESALIDA), 0) / 60.00 as decimal(18,2)) - ISNULL(H.HORASFUERAS, 0),0) AS CANTHoras
      ,CASE 
			WHEN ISNULL(H.TRABAJAHOY, 0) = 0  THEN 0
			WHEN ISNULL(CF.Estado, 0) = 0 THEN 1
			WHEN PF.Posicion is null OR ( PF.Posicion is not null AND H.PoncheEntrada is null) THEN 0 
			ELSE 1
		END TRABAJAHOY
      ,H.ADMINISTRATIVO
      ,H.HORASEXTRAS
      ,H.HORASDESCONTADAS
      ,H.CANTHORASPERMISO
      ,H.HORASFUERAS
      ,H.FechaNacimiento
      ,H.FechaIngreso
      ,H.HORASEXTRASPLA
      ,H.MOTIVOSPLA
	  ,CASE
		WHEN A.AUDES IS NOT NULL AND A.AUTEL = 1 THEN CAST(A.AUTEL AS BIT)
		ELSE CAST(ISNULL(POD.Selected, 0) AS BIT)  
	   END OffPremise
	  ,CASE
			WHEN H.HORAINI IS NULL THEN null
			WHEN H.CANTHORASPERMISO IS NULL THEN H.HORAINI
			ELSE DATEADD(HOUR,H.CANTHORASPERMISO, H.HORAINI) 
	  END REALHORAINI
FROM dbo.Horario H
LEFT JOIN dbo.Calendario_Festivo CF
ON H.Fecha = CF.Fecha
LEFT JOIN dbo.Posiciones_Feriados PF
ON H.Posicion = PF.Posicion
LEFT JOIN dbo.PosicionOffPremiseDetails POD
ON H.CODIGOEMPLEADO = POD.CodigoEmpleado
LEFT JOIN dbo.Ausentismo A
ON H.AUCOD = A.AUCOD
GO


