
/****** Object:  Table [dbo].[Posiciones_Feriados]    Script Date: 6/16/2022 10:49:24 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Posiciones_Feriados](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Posicion] [nvarchar](400) NULL,
 CONSTRAINT [PK_Posiciones_Feriados] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


